version = 1
SPDX-PackageName = "Enterprise"
SPDX-PackageSupplier = "ss14-ganimed <spacestation14enterprise@gmail.com>"
SPDX-PackageDownloadLocation = "https://station-enterprise.space"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Textures/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["**.txt", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**Ganimed/**", "**ganimed/**", "**Ganymede/**", "**ganymede/**", "**Enterprise/**", "**enterprise/**", "**ENT/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2023-2026 Contributors to Enterprise (Ganimed14) project", "2023-2026 Enterprise <spacestation14enterprise@gmail.com>"]
SPDX-License-Identifier = "AGPL-3.0-or-later
