using System.Linq;
using Content.Client.ADT.UI.Chat; 
using Content.Client.UserInterface.Systems.Chat.Controls;
using Content.Shared.Chat;
using Content.Shared.Input;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Shared.Configuration;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Utility;
using Content.Shared.CCVar;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.UserInterface.Systems.Chat.Widgets;

[GenerateTypedNameReferences]
[Virtual]
public partial class ChatBox : UIWidget
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly ILogManager _log = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!; // Ganimed, EE - Chat stacking
    [Dependency] private readonly ILocalizationManager _loc = default!; // Ganimed, EE - Chat stacking

    private readonly ISawmill _sawmill;
    private readonly ChatUIController _controller;
    private readonly ChatSearchController _searchController; // ADT-Tweak

    public bool Main { get; set; }

    public string SearchFilter { get; private set; } = string.Empty; // ADT-Tweak

    public ChatSelectChannel SelectedChannel => ChatInput.ChannelSelector.SelectedChannel;

    // Ganimed, EE - Chat stacking
    private int _chatStackAmount = 0;
    private bool _chatStackEnabled => _chatStackAmount > 0;
    private List<ChatStackData> _chatStackList;
    // Ganimed, EE - Chat stacking

    public ChatBox()
    {
        RobustXamlLoader.Load(this);
        _sawmill = _log.GetSawmill("chat");

        ChatInput.Input.OnTextEntered += OnTextEntered;
        ChatInput.Input.OnKeyBindDown += OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged += OnTextChanged;
        ChatInput.Input.OnFocusEnter += OnFocusEnter;
        ChatInput.Input.OnFocusExit += OnFocusExit;
        ChatInput.ChannelSelector.OnChannelSelect += OnChannelSelect;
        ChatInput.FilterButton.Popup.OnChannelFilter += OnChannelFilter;
        ChatInput.FilterButton.Popup.OnNewHighlights += OnNewHighlights;
        // ADT-Tweak start
        ChatInput.OnSearchButtonPressed += ToggleSearch;
        ChatSearch.OnSearchChanged += OnSearchTextChanged;
        ChatSearch.OnSearchClosed += CloseSearch;
        // ADT-Tweak end
        _controller = UserInterfaceManager.GetUIController<ChatUIController>();
        _searchController = UserInterfaceManager.GetUIController<ChatSearchController>(); // ADT-Tweak
        _controller.MessageAdded += OnMessageAdded;
        _controller.HighlightsUpdated += OnHighlightsUpdated;
        _controller.RegisterChat(this);

        // Ganimed, EE - Chat stacking
        _chatStackList = new List<ChatStackData>(_chatStackAmount);
        _cfg.OnValueChanged(CCVars.ChatStackLastLines, UpdateChatStack, true);
        //  Ganimed, EE end - Chat stacking
    }

    // Ganimed, EE - Chat stacking
    private void UpdateChatStack(int value)
    {
        _chatStackAmount = value >= 0 ? value : 0;
        Repopulate();
    }

    private void OnTextEntered(LineEditEventArgs args)
    {
        _controller.SendMessage(this, SelectedChannel);
    }

    private void OnMessageAdded(ChatMessage msg)
    {
        _sawmill.Debug($"{msg.Channel}: {msg.Message}");
        if (!ChatInput.FilterButton.Popup.IsActive(msg.Channel))
        {
            return;
        }

        // ADT-Tweak start
        if (!string.IsNullOrWhiteSpace(SearchFilter)
            && !_searchController.MatchesQuery(msg, SearchFilter))
        {
            return;
        }
        // ADT-Tweak end

        if (msg is { Read: false, AudioPath: { } })
            _entManager.System<AudioSystem>().PlayGlobal(msg.AudioPath, Filter.Local(), false, AudioParams.Default.WithVolume(msg.AudioVolume));

        msg.Read = true;

        var color = msg.MessageColorOverride ?? msg.Channel.TextColor();

        // Ganimed, EE - Chat stacking
        var index = _chatStackList.FindIndex(data => data.WrappedMessage == msg.WrappedMessage);

        if (index == -1) // this also handles chatstack being disabled, since FindIndex won't find anything in an empty array
        {
            TrackNewMessage(msg.WrappedMessage, color);
            AddLine(msg.WrappedMessage, color);
            return;
        }

        UpdateRepeatingLine(index);
        // Ganimed, End EE - Chat stacking
    }

    /// <summary>
    /// Removing and then adding instantly nudges the chat window up before slowly dragging it back down, which makes the whole chat log shake.
    /// With rapid enough updates, the whole chat becomes unreadable.
    /// Adding first and then removing does not produce any visual effects.
    /// The other option is to duplicate OutputPanel functionality and everything internal to the engine it relies on.
    /// But OutputPanel relies on directly setting Control.Position for control embedding. (which is not exposed to Content.)
    /// Thanks robustengine, very cool.
    /// </summary>
    /// <remarks>
    /// zero index is the very last line in chat, 1 is the line before the last one, 2 is the line before that, etc.
    /// </remarks>
    // Ganimed, EE - Chat stacking
    private void UpdateRepeatingLine(int index)
    {
        _chatStackList[index].RepeatCount++;
        for (var i = index; i >= 0; i--)
        {
            var data = _chatStackList[i];
            AddLine(data.WrappedMessage, data.ColorOverride, data.RepeatCount);
            Contents.RemoveEntry(Index.FromEnd(index + 2));
        }
    }

    // Ganimed, EE - Chat stacking
    private void TrackNewMessage(string wrappedMessage, Color colorOverride)
    {
        if (!_chatStackEnabled)
            return;

        if (_chatStackList.Count == _chatStackList.Capacity)
            _chatStackList.RemoveAt(_chatStackList.Capacity - 1);

        _chatStackList.Insert(0, new ChatStackData(wrappedMessage, colorOverride));
    }

    // ADT-Tweak start
    public void SetSearchFilter(string filter)
    {
        SearchFilter = filter.Trim();
        Repopulate();
    }

    private void ToggleSearch()
    {
        if (SearchPanel.Visible)
        {
            CloseSearch();
        }
        else
        {
            OpenSearch();
        }
    }

    private void OpenSearch()
    {
        SearchPanel.Visible = true;
        ChatSearch.FocusSearch();
    }

    private void CloseSearch()
    {
        if (!SearchPanel.Visible)
            return;

        SearchPanel.Visible = false;
        ChatSearch.SearchInput.Clear();
        _searchController.ClearSearch(this);
    }

    private void OnSearchTextChanged(string query)
    {
        _searchController.SetSearch(this, query);
    }
    // ADT-Tweak end

    private void OnHighlightsUpdated(string highlights)
    {
        ChatInput.FilterButton.Popup.UpdateHighlights(highlights);
    }

    private void OnChannelSelect(ChatSelectChannel channel)
    {
        _controller.UpdateSelectedChannel(this);
    }

    public void Repopulate()
    {
        // ADT-Tweak start
        _controller.MessageAdded -= OnMessageAdded;

        Contents.Clear();
        // ADT-Tweak end
        _chatStackList = new List<ChatStackData>(_chatStackAmount); // Ganimed, EE - Chat stacking

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }

        _controller.MessageAdded += OnMessageAdded; // ADT-Tweak 
    }

    private void OnChannelFilter(ChatChannel channel, bool active)
    {
        // ADT-Tweak start
        _controller.MessageAdded -= OnMessageAdded;

        Contents.Clear();
        // ADT-Tweak end

        foreach (var message in _controller.History)
        {
            OnMessageAdded(message.Item2);
        }

        _controller.MessageAdded += OnMessageAdded; // ADT-Tweak 

        if (active)
        {
            _controller.ClearUnfilteredUnreads(channel);
        }
    }

    private void OnNewHighlights(string highlighs)
    {
        _controller.UpdateHighlights(highlighs);
    }

    public void AddLine(string message, Color color, int repeat = 0) // Ganimed - Chat stacking - repeatr)
    {
        int sizeIncrease = 11;

        var formatted = new FormattedMessage(4); // Ganimed, EE - Chat stacking - up from
        formatted.PushColor(color);
        formatted.AddMarkupPermissive(message); // ADT-Tweak
        formatted.Pop();

        // Ganimed, EE - Chat stacking
        if (repeat != 0)
        {
            var displayRepeat = repeat + 1;
            formatted.AddMarkupOrThrow(_loc.GetString("chat-system-repeated-message-counter",
                                ("count", displayRepeat),
                                ("size", sizeIncrease)
                                ));
        }
        Contents.AddMessage(formatted, tagsAllowed: null);
        // Ganimed, End EE - Chat stacking
    }

    public void Focus(ChatSelectChannel? channel = null)
    {
        var input = ChatInput.Input;
        var selectStart = Index.End;

        if (channel != null)
            ChatInput.ChannelSelector.Select(channel.Value);

        input.IgnoreNext = true;
        input.GrabKeyboardFocus();

        input.CursorPosition = input.Text.Length;
        input.SelectionStart = selectStart.GetOffset(input.Text.Length);
    }

    public void CycleChatChannel(bool forward)
    {
        var idx = Array.IndexOf(ChannelSelectorPopup.ChannelSelectorOrder, SelectedChannel);
        do
        {
            // go over every channel until we find one we can actually select.
            idx += forward ? 1 : -1;
            idx = MathHelper.Mod(idx, ChannelSelectorPopup.ChannelSelectorOrder.Length);
        } while ((_controller.SelectableChannels & ChannelSelectorPopup.ChannelSelectorOrder[idx]) == 0);

        SafelySelectChannel(ChannelSelectorPopup.ChannelSelectorOrder[idx]);
    }

    public void SafelySelectChannel(ChatSelectChannel toSelect)
    {
        toSelect = _controller.MapLocalIfGhost(toSelect);
        if ((_controller.SelectableChannels & toSelect) == 0)
            return;

        ChatInput.ChannelSelector.Select(toSelect);
    }

    private void OnInputKeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextReleaseFocus)
        {
            ChatInput.Input.ReleaseKeyboardFocus();
            ChatInput.Input.Clear();
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelForward)
        {
            CycleChatChannel(true);
            args.Handle();
            return;
        }

        if (args.Function == ContentKeyFunctions.CycleChatChannelBackward)
        {
            CycleChatChannel(false);
            args.Handle();
        }
    }

    private void OnTextChanged(LineEditEventArgs args)
    {
        // Update channel select button to correct channel if we have a prefix.
        _controller.UpdateSelectedChannel(this);

        // Warn typing indicator about change
        var (prefixChannel, _, _) = _controller.SplitInputContents(ChatInput.Input.Text); // Ganimed-Add (Typing indicator color based on chat type)
        _controller.NotifyChatTextChange((ChatChannel)(prefixChannel == ChatSelectChannel.None ? SelectedChannel : prefixChannel)); // Ganimed-Edit (Added (ChatChannel)(prefixChannel == ChatSelectChannel.None ? SelectedChannel : prefixChannel))
    }

    private void OnFocusEnter(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(true, (ChatChannel)SelectedChannel); // Ganimed-Edit: Typing indicator color based on chat type (Added (ChatChannel)SelectedChannel)
    }

    private void OnFocusExit(LineEditEventArgs args)
    {
        // Warn typing indicator about focus
        _controller.NotifyChatFocus(false, (ChatChannel)SelectedChannel); // Ganimed-Edit: Typing indicator color based on chat type (Added (ChatChannel)SelectedChannel)
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing) return;
        _controller.UnregisterChat(this);
        ChatInput.Input.OnTextEntered -= OnTextEntered;
        ChatInput.Input.OnKeyBindDown -= OnInputKeyBindDown;
        ChatInput.Input.OnTextChanged -= OnTextChanged;
        ChatInput.ChannelSelector.OnChannelSelect -= OnChannelSelect;
        _cfg.UnsubValueChanged(CCVars.ChatStackLastLines, UpdateChatStack); // Ganimed, EE - Chat stacking
        // ADT-Tweak start
        ChatInput.OnSearchButtonPressed -= ToggleSearch;
        ChatSearch.OnSearchChanged -= OnSearchTextChanged;
        ChatSearch.OnSearchClosed -= CloseSearch;
        // ADT-Tweak end
    }
}

// Ganimed, EE - StackChat
public sealed partial class ChatStackData
{
    public string WrappedMessage;
    public Color ColorOverride;
    public int RepeatCount = 0;
    public ChatStackData(string wrappedMessage, Color colorOverride)
    {
        WrappedMessage = wrappedMessage;
        ColorOverride = colorOverride;
    }
}