// SPDX-FileCopyrightText: 2026 Gorox221 <139872389+Gorox221@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Ganimed.Research.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using RobustRichTextLabel = Robust.Client.UserInterface.Controls.RichTextLabel;

namespace Content.Client._Ganimed.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ExperimentScannerMenu : FancyWindow
{
    public Action<string>? OnSelectOrder;
    public Action? OnAbandonOrder;
    public Action<string>? OnSkipOrder;
    public Action? OnSelectServer;

    private TimeSpan _untilNextSkip = TimeSpan.Zero;
    private readonly List<Button> _skipButtons = new();

    public ExperimentScannerMenu()
    {
        RobustXamlLoader.Load(this);
        MainTabs.SetTabTitle(0, Loc.GetString("experiment-scanner-tab-available"));
        MainTabs.SetTabTitle(1, Loc.GetString("experiment-scanner-tab-active"));
        AbandonButton.OnPressed += _ => OnAbandonOrder?.Invoke();
        ServerButton.OnPressed += _ => OnSelectServer?.Invoke();
    }

    public void UpdateState(ExperimentScannerState state)
    {
        _untilNextSkip = state.UntilNextSkip;
        if (state.HasSelectedServer)
        {
            ServerStatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
                Loc.GetString("experiment-scanner-server-selected",
                    ("server", state.SelectedServerName ?? "-"))));
        }
        else
        {
            ServerStatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
                Loc.GetString("experiment-scanner-server-not-selected")));
        }

        AvailableContainer.DisposeAllChildren();
        _skipButtons.Clear();
        foreach (var order in state.Available)
        {
            var panel = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 0, 8),
                HorizontalExpand = true
            };
            var name = new RobustRichTextLabel();
            name.SetMessage(FormattedMessage.FromMarkupPermissive(
                Loc.GetString("experiment-scanner-order-name", ("name", order.Name))));
            panel.AddChild(name);
            var desc = new RobustRichTextLabel
            {
                HorizontalExpand = true
            };
            desc.SetMessage(FormattedMessage.FromMarkupPermissive(order.Description));
            panel.AddChild(desc);
            panel.AddChild(new RobustRichTextLabel { Text = Loc.GetString("experiment-scanner-progress", ("current", order.ProgressCurrent), ("target", order.ProgressTarget)) });
            var reward = new RobustRichTextLabel();
            reward.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("experiment-scanner-reward", ("points", order.RewardPoints))));
            panel.AddChild(reward);

            var buttons = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal
            };
            var selectButton = new Button
            {
                Text = Loc.GetString("experiment-scanner-take"),
                HorizontalExpand = true
            };
            selectButton.OnPressed += _ => OnSelectOrder?.Invoke(order.Id);
            buttons.AddChild(selectButton);

            var skipButton = new Button
            {
                Text = Loc.GetString("experiment-scanner-skip"),
                HorizontalExpand = true
            };
            skipButton.OnPressed += _ => OnSkipOrder?.Invoke(order.Id);
            _skipButtons.Add(skipButton);
            buttons.AddChild(skipButton);
            panel.AddChild(buttons);
            AvailableContainer.AddChild(panel);
        }

        if (state.Active == null)
        {
            NoActiveLabel.Visible = true;
            ActiveContainer.Visible = false;
            ActiveTimeLabel.Text = string.Empty;
            return;
        }

        NoActiveLabel.Visible = false;
        ActiveContainer.Visible = true;
        ActiveNameLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("experiment-scanner-order-name", ("name", state.Active.Name))));
        ActiveDescLabel.SetMessage(FormattedMessage.FromMarkupPermissive(state.Active.Description));
        ActiveProgressLabel.Text = Loc.GetString("experiment-scanner-progress", ("current", state.Active.ProgressCurrent), ("target", state.Active.ProgressTarget));
        ActiveRewardLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("experiment-scanner-reward", ("points", state.Active.RewardPoints))));
        ActiveTimeLabel.Text = state.Active.TimeRemaining is { } wait && wait > TimeSpan.Zero
            ? Loc.GetString("experiment-scanner-wait-rescan", ("time", wait.ToString("mm\\:ss")))
            : string.Empty;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _untilNextSkip -= TimeSpan.FromSeconds(args.DeltaSeconds);
        if (_untilNextSkip > TimeSpan.Zero)
        {
            foreach (var skipButton in _skipButtons)
            {
                skipButton.Disabled = true;
                skipButton.Text = _untilNextSkip.ToString("mm\\:ss");
            }
            return;
        }

        foreach (var skipButton in _skipButtons)
        {
            skipButton.Disabled = false;
            skipButton.Text = Loc.GetString("experiment-scanner-skip");
        }
    }
}
