- type: job
  id: ADTJobUSSPArmyOfficer
  name: job-name-ussp-officer # Ganimed-Edit (job-name-ussp-army-officer)
  description: job-description-ussp-army-officer
  playTimeTracker: JobADTUSSPArmyOfficer # Заглушка
  setPreference: false
  icon: "JobIconUSSPOfficer" # Ganimed-Edit (JobIconADTUSSPArmyOfficer)
  access:
  - Maintenance
  - External
  canBeAntag: false
