using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Ganimed.Chemistry;
using Content.Shared._Ganimed.Chemistry.HPLC;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Ganimed.Chemistry.HPLC;

[GenerateTypedNameReferences]
public sealed partial class HplcWindow : FancyWindow
{
    public event Action<string>? ReagentSelected;

    public HplcWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(HplcBoundUserInterfaceState state)
    {
        BuildBeakerUi(InputContainerInfo, state.InputBeaker, isInput: true, state);
        BuildBeakerUi(OutputContainerInfo, state.OutputBeaker, isInput: false, state);

        var inputReagents = state.InputBeaker?.Reagents ?? [];
        StartButton.Disabled = state.Processing
                               || state.OutputBeaker == null
                               || state.SelectedReagent == null
                               || !inputReagents.Any(r => r.Prototype == state.SelectedReagent && r.CanPurify);

        EjectButton.Disabled = state.Processing;
        OutputEjectButton.Disabled = state.Processing || state.OutputBeaker == null;

        if (state.Processing)
        {
            EtaLabel.SetMessage(Loc.GetString("hplc-window-eta",
                ("seconds", Math.Ceiling(state.RemainingSeconds))));
        }
        else if (state.SelectedReagent != null && state.OutputBeaker == null)
        {
            EtaLabel.SetMessage(Loc.GetString("hplc-window-output-required"));
        }
        else if (state.SelectedReagent != null)
        {
            EtaLabel.SetMessage(Loc.GetString("hplc-window-select-hint"));
        }
        else
        {
            EtaLabel.SetMessage(Loc.GetString("hplc-window-no-selection"));
        }
    }

    private void BuildBeakerUi(
        BoxContainer container,
        HplcBeakerState? beaker,
        bool isInput,
        HplcBoundUserInterfaceState state)
    {
        container.Children.Clear();

        if (beaker == null)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString(isInput
                    ? "hplc-window-no-input-beaker"
                    : "hplc-window-output-missing"),
            });
            return;
        }

        var ph = beaker.SolutionPH?.ToString("0.0") ?? ChemistryPH.NeutralPH.ToString("0.0");
        container.AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Children =
            {
                new Label { Text = $"{beaker.DisplayName}: " },
                new Label
                {
                    Text = Loc.GetString("hplc-window-fill-with-ph",
                        ("volume", beaker.Volume),
                        ("max", beaker.MaxVolume),
                        ("ph", ph)),
                    StyleClasses = { StyleClass.LabelWeak },
                },
            },
        });

        if (beaker.Reagents.Count == 0)
        {
            container.AddChild(new Label { Text = Loc.GetString("hplc-window-beaker-empty") });
            return;
        }

        var rowCount = 0;
        foreach (var reagent in beaker.Reagents)
        {
            container.AddChild(BuildReagentRow(reagent, rowCount++, isInput, state));
        }
    }

    private Control BuildReagentRow(
        HplcReagentEntry reagent,
        int rowCount,
        bool isInput,
        HplcBoundUserInterfaceState state)
    {
        var rowColor1 = Color.FromHex("#1B1B1E");
        var rowColor2 = Color.FromHex("#202025");
        var currentRowColor = rowCount % 2 == 1 ? rowColor1 : rowColor2;

        var reagentColor = Color.TryFromHex(reagent.ColorHex) ?? currentRowColor;

        var rowContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        if (isInput)
        {
            var selectButton = new Button
            {
                Text = "✓",
                ToggleMode = true,
                Pressed = state.SelectedReagent == reagent.Prototype,
                Disabled = state.Processing || !reagent.CanPurify,
                StyleClasses = { StyleNano.StyleClassButtonColorGreen, StyleNano.ButtonSquare },
                MinSize = new Vector2(30, 0),
            };
            selectButton.OnPressed += _ => ReagentSelected?.Invoke(reagent.Prototype);
            rowContainer.AddChild(selectButton);
        }

        rowContainer.AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Children =
            {
                new Label { Text = $"{reagent.Name}: " },
                new Label
                {
                    Text = Loc.GetString("hplc-window-reagent-entry",
                        ("volume", reagent.Volume),
                        ("purity", Math.Round(reagent.PurityPercent))),
                    StyleClasses = { StyleClass.LabelWeak },
                },
            },
        });

        rowContainer.AddChild(new PanelContainer
        {
            VerticalExpand = true,
            MinWidth = 4,
            MaxWidth = 4,
            Margin = new Thickness(4, 1, 0, 1),
            PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor },
        });

        return new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat(currentRowColor),
            Children = { rowContainer },
        };
    }
}
