using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Ganimed.Chemistry;
using Content.Shared._Ganimed.Chemistry.ReactionChamber;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Ganimed.Chemistry.ReactionChamber;

[GenerateTypedNameReferences]
public sealed partial class ReactionChamberWindow : FancyWindow
{
    public event Action<string, bool, bool>? TransferRequested;
    public event Action<int>? TransferAmountChanged;
    public event Action<List<int>>? AmountsChanged;
    public event Action? ConfigureProgramsRequested;
    public event Action<int>? ProgramSelected;
    public event Action? StartRequested;
    public event Action? StopRequested;

    private List<int> _amounts = SharedReactionChamber.CreateDefaultAmounts();
    private int _transferAmount = 5;
    private bool _updatingProgramSelector;

    public ReactionChamberWindow()
    {
        RobustXamlLoader.Load(this);

        AmountLineEdit.OnTextEntered += args => ValidateAmount(args.Text);
        ConfigureProgramsButton.OnPressed += _ => ConfigureProgramsRequested?.Invoke();
        StartButton.OnPressed += _ => StartRequested?.Invoke();
        StopButton.OnPressed += _ => StopRequested?.Invoke();
        ProgramSelector.OnItemSelected += args =>
        {
            if (_updatingProgramSelector)
                return;

            ProgramSelected?.Invoke(args.Id);
        };

        RebuildAmountButtons();
    }

    public void UpdateState(ReactionChamberBoundUserInterfaceState state)
    {
        if (!_amounts.SequenceEqual(state.Amounts))
        {
            _amounts = state.Amounts.ToList();
            RebuildAmountButtons();
        }

        if (_transferAmount != state.TransferAmount)
        {
            _transferAmount = state.TransferAmount;
            AmountLineEdit.SetText(_transferAmount.ToString());
        }

        BuildSolutionUi(
            BufferContainerInfo,
            state.BufferReagents,
            state.BufferVolume,
            state.BufferMaxVolume,
            state.BufferSolutionPH,
            containerName: Loc.GetString("reaction-chamber-window-buffer-label"),
            fromBuffer: true,
            running: state.Running);

        BuildSolutionUi(
            BeakerContainerInfo,
            state.Beaker?.Reagents ?? new List<ReactionChamberReagentEntry>(),
            state.Beaker?.Volume ?? FixedPoint2.Zero,
            state.Beaker?.MaxVolume ?? FixedPoint2.Zero,
            state.Beaker?.SolutionPH ?? ChemistryPH.NeutralPH,
            containerName: state.Beaker?.DisplayName,
            fromBuffer: false,
            running: state.Running,
            beakerMissing: state.Beaker == null);

        UpdateProgramSelector(state);
        UpdateStatus(state);

        EjectButton.Disabled = state.Running || state.Beaker == null;
        ConfigureProgramsButton.Disabled = state.Running;
        StartButton.Disabled = state.Running
                               || state.SelectedProgramIndex < 0
                               || state.Beaker == null
                               || state.Programs.Count == 0;
        StopButton.Disabled = !state.Running;
        ProgramSelector.Disabled = state.Running;
    }

    private void UpdateProgramSelector(ReactionChamberBoundUserInterfaceState state)
    {
        _updatingProgramSelector = true;
        ProgramSelector.Clear();

        if (state.Programs.Count == 0)
        {
            ProgramSelector.AddItem(Loc.GetString("reaction-chamber-window-no-programs"), -1);
            ProgramSelector.SelectId(-1);
        }
        else
        {
            for (var i = 0; i < state.Programs.Count; i++)
            {
                var program = state.Programs[i];
                ProgramSelector.AddItem(
                    Loc.GetString("reaction-chamber-window-program-entry",
                        ("name", program.Name),
                        ("steps", program.StepCount)),
                    i);
            }

            var selected = state.SelectedProgramIndex >= 0 && state.SelectedProgramIndex < state.Programs.Count
                ? state.SelectedProgramIndex
                : 0;
            ProgramSelector.SelectId(selected);
        }

        _updatingProgramSelector = false;
    }

    private void UpdateStatus(ReactionChamberBoundUserInterfaceState state)
    {
        if (state.Running)
        {
            if (state.WaitingForTemperature)
            {
                StatusLabel.SetMessage(Loc.GetString("reaction-chamber-window-status-temperature",
                    ("current", state.BeakerTemperature.ToString("0.0")),
                    ("target", state.TargetBeakerTemperature.ToString("0")),
                    ("step", state.CurrentStepDescription ?? "?")));
                return;
            }

            if (state.WaitRemainingSeconds > 0f)
            {
                StatusLabel.SetMessage(Loc.GetString("reaction-chamber-window-status-wait",
                    ("seconds", Math.Ceiling(state.WaitRemainingSeconds)),
                    ("step", state.CurrentStepDescription ?? "?")));
            }
            else
            {
                StatusLabel.SetMessage(Loc.GetString("reaction-chamber-window-status-running",
                    ("step", state.CurrentStepDescription ?? "?")));
            }

            return;
        }

        if (state.Beaker == null)
        {
            StatusLabel.SetMessage(Loc.GetString("reaction-chamber-window-status-no-beaker"));
            return;
        }

        StatusLabel.SetMessage(Loc.GetString("reaction-chamber-window-status-idle"));
    }

    private void BuildSolutionUi(
        BoxContainer container,
        List<ReactionChamberReagentEntry> reagents,
        FixedPoint2 volume,
        FixedPoint2 maxVolume,
        float solutionPH,
        string? containerName,
        bool fromBuffer,
        bool running,
        bool beakerMissing = false)
    {
        container.Children.Clear();

        if (beakerMissing)
        {
            container.AddChild(new Label { Text = Loc.GetString("reaction-chamber-window-no-beaker") });
            return;
        }

        container.AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Children =
            {
                new Label { Text = $"{containerName}: " },
                new Label
                {
                    Text = Loc.GetString("chem-master-window-fill-with-ph-label-text",
                        ("currentVolume", volume),
                        ("maxVolume", maxVolume),
                        ("ph", solutionPH.ToString("0.0"))),
                    StyleClasses = { StyleClass.LabelWeak },
                },
            },
        });

        if (reagents.Count == 0)
        {
            container.AddChild(new Label { Text = Loc.GetString("reaction-chamber-window-empty") });
            return;
        }

        var rowCount = 0;
        foreach (var reagent in reagents)
        {
            container.AddChild(BuildReagentRow(reagent, rowCount++, fromBuffer, running));
        }
    }

    private Control BuildReagentRow(ReactionChamberReagentEntry reagent, int rowCount, bool fromBuffer, bool running)
    {
        var rowColor1 = Color.FromHex("#1B1B1E");
        var rowColor2 = Color.FromHex("#202025");
        var currentRowColor = rowCount % 2 == 1 ? rowColor1 : rowColor2;
        var reagentColor = Color.TryFromHex(reagent.ColorHex) ?? currentRowColor;

        var rowContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            MinSize = new Vector2(0, 28),
        };

        rowContainer.AddChild(new BoxContainer
        {
            MinWidth = 130,
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Children =
            {
                new Label
                {
                    Text = $"{reagent.Name}: ",
                    HorizontalAlignment = HAlignment.Left,
                },
                new Label
                {
                    Text = Loc.GetString("chem-master-window-quantity-with-ph-label-text",
                        ("quantity", reagent.Volume),
                        ("ph", reagent.Ph.ToString("0.0"))),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                    HorizontalAlignment = HAlignment.Left,
                },
            },
        });

        rowContainer.AddChild(new Control { HorizontalExpand = true });

        rowContainer.AddChild(new PanelContainer
        {
            VerticalExpand = true,
            MinWidth = 4,
            PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor },
            Margin = new Thickness(0, 1),
        });

        var transferButton = new Button
        {
            Text = Loc.GetString("chem-master-window-transfer-button"),
            StyleClasses = { StyleNano.ButtonSquare },
            Disabled = running,
        };
        transferButton.OnPressed += _ => TransferRequested?.Invoke(reagent.Prototype, fromBuffer, false);
        rowContainer.AddChild(transferButton);

        var transferAllButton = new Button
        {
            Text = Loc.GetString("chem-master-window-buffer-all-amount"),
            StyleClasses = { StyleNano.ButtonOpenLeft },
            Disabled = running,
        };
        transferAllButton.OnPressed += _ => TransferRequested?.Invoke(reagent.Prototype, fromBuffer, true);
        rowContainer.AddChild(transferAllButton);

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = currentRowColor },
            HorizontalExpand = true,
            Children = { rowContainer },
        };
    }

    private void RebuildAmountButtons()
    {
        AmountButtons.Children.Clear();

        foreach (var amount in _amounts)
        {
            var button = new Button { Text = amount.ToString(), MinSize = new Vector2(42, 0) };
            button.OnPressed += _ => SetTransferAmount(amount);
            AmountButtons.AddChild(button);
        }
    }

    private void SetTransferAmount(int amount)
    {
        _transferAmount = amount;
        AmountLineEdit.SetText(amount.ToString());
        TransferAmountChanged?.Invoke(amount);
    }

    private void ValidateAmount(string text)
    {
        if (!int.TryParse(text, out var amount) || amount <= 0 || amount > ReactionChamberComponent.DefaultBufferMaxVolume)
        {
            AmountLineEdit.SetText(_transferAmount.ToString());
            return;
        }

        _transferAmount = amount;
        TransferAmountChanged?.Invoke(amount);
    }
}
