name: "Labels: Approve"

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  remove_label:
    permissions:
      pull-requests: write
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Remove labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            S: Needs Review
            S: Awaiting Changes

      - name: Add "Approved" label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "S: Approved"
          github_token: ${{ secrets.GITHUB_TOKEN }}
